QuantEcon/sphinxcontrib-jupyter

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/builders/jupyter.py
- sphinxcontrib/jupyter/writers/translate_code.py
- tests/conf.py
This removes the ability to add header blocks to every produced notebook which were defined in the ``conf.py`` file. This was initially used to add some code such as to switch ``autosave`` off for every produced notebook. 
This will be replaced with the ability to specify a header rst which can be used to add in RST and/or code to the top of every produced notebook. This is currently called ``welcome_message`` but this should be renamed as ``header_rst``.
> Removes the ability to add notebook headers from the conf.py file. 

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/writers/translate_code.py
- tests/conf.py
This PR updates ``jupyter_welcome_message`` option in the ``conf.py`` to ``jupyter_header_block``.
One can add a header to generated notebooks by adding an ``rst`` file and setting it in the ``conf.py`` file. 
```
jupyter_header_block = "welcome.rst"
```
> Update jupyter_welcome_message to be more unified terminology ``header_block``

- sphinxcontrib/jupyter/writers/utils.py
Resolves @jlperla's issue QuantEcon/sphinxcontrib-jupyter.minimal#2, which was fixed by switching UNIX-style delimiters `/` in a file to Windows ones `\`. This PR replaces them with a generic delimiter `os.sep`. 
Note: There's one place in this function where `/` is still hardcoded, but since it didn't seem to break anything, I didn't want to touch it. I left a comment there.
> resolve error with windows delimiters

- README.rst
- sphinxcontrib/jupyter/writers/translate_all.py
- tests/index.rst
- tests/ipynb/code_blocks.ipynb
- tests/ipynb/notes.ipynb
- tests/notes.rst
> add support for note node type as blockquote markdown

- README.rst
- sphinxcontrib/jupyter/writers/translate_all.py
- tests/index.rst
- tests/ipynb/only.ipynb
- tests/only.rst
add support for skipping only content relating to other builders and associated test
this will skip items like:
```
.. only:: html
```
> FEAT: Add support to skip only directives that are not jupyter

- sphinxcontrib/jupyter/writers/translate_all.py
- tests/index.rst
- tests/inline.rst
- tests/ipynb/code_blocks.ipynb
- tests/ipynb/inline.ipynb
- tests/ipynb/simple_notebook.ipynb
This PR adds support for parsing inline literals and adds a test case for inline elements.
These include elements in RST such as
```rst
This is a ``import numpy as np`` inline literal
```
> FEAT: Add support for inline literal markup in RST

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/transform/__init__.py
- tests/Makefile
- tests/ipynb/only.ipynb
- tests/only.rst
This PR adds a transform to parse ``jupyter_allow_html_only`` configuration to include html only blocks in generated jupyter notebooks
The default configuration value is `False` therefore by default the blocks that are included are:
```
.. only:: jupyter
```
blocks
> FEAT: allow jupyter notebooks to capture html only blocks in output

- sphinxcontrib/jupyter/writers/translate_all.py
- tests/ipynb/code_blocks.ipynb
- tests/ipynb/lists.ipynb
- tests/lists.rst
This PR fixes an issue which generated an `odd` number of spaces when translating to markdown nested lists which broke rendering.
> FIX: fix issue with odd number of spaces breaking nested lists

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/writers/translate_code.py
- tests/code_synonyms.rst
- tests/conf.py
- tests/index.rst
- tests/ipynb/code_synonyms.ipynb
This PR will allow the use of ``python`` and ``ipython`` (for example) to be in a single notebook and they will both be included as executable code-blocks.
> FEAT: adding support for language synonyms such as python and ipython

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/writers/translate_all.py
- sphinxcontrib/jupyter/writers/translate_code.py
This PR allows for links to be formed using ``html`` instead of ``ipynb`` extensions for projects that want to compile using ``nbconvert --to=html``. This will ensure links generated are linkable at the ``html`` level. 
It is activated in ``conf.py`` by adding ``jupyter_target_html = True``
> FEAT: allow html targeting in links for use with nbconvert

- sphinxcontrib/jupyter/writers/translate_all.py
When ``jupyter_target_html`` is set to `True` footnotes `<sup>` markers in the text will be added to markdown cells as pure html to allow passthrough for use mainly with `nbconvert` when targeting `html` output.
> FEAT: Add html target for adding footnotes (to allow nbconvert passthrough)

- sphinxcontrib/jupyter/writers/translate_all.py
This PR enables clickable footnotes (between within text and the Footnote listing and vice versa) and is enabled using ``jupyter_target_html=True`` as it relies on `html`.
> FEAT: Allow target html for footnotes

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/writers/translate_code.py
- sphinxcontrib/jupyter/writers/utils.py
This PR adds a global ignore option for code blocks specified with ``:class: skip-test``. 
This can be enabled in the conf.py file through ``jupyter_ignore_skip_test=True`` or with ``sphinx-build`` using `D` flag and specifying ``jupyter_ignore_skip_test=1``
> FEAT: add ignore for globally skipping skip-test flag in code-blocks

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/writers/translate_all.py
- sphinxcontrib/jupyter/writers/translate_code.py
- tests/conf.py
This PR adds the ability to specify a web location for embedded images in notebooks. This reduces the need to track `_static` assets as long as they are published in a web location. This PR addresses #116. 
The option ``jupyter_images_urlpath = "https://<address>/"`` can be specified in the ``conf.py`` file which will swap the relative reference to ``_static`` for a web location. 
The default action is to use local file references in a `_static` folder with ``jupyter_images_urlpath = None``
> FEAT: add urlprefix capability for images in notebooks

- sphinxcontrib/jupyter/writers/utils.py
- tests/code_blocks.rst
- tests/ipynb/code_blocks.ipynb
This PR simply removes `none` from the markdown code-block when writing notebooks. This assists when rendering notebooks to html (via nbconvert).
> FIX: fix markdown when no language is specified for highlighting

- sphinxcontrib/jupyter/writers/utils.py
- tests/ipynb/code_blocks.ipynb
This will enable better rendering when converting ipynb to html.
> FIX: change to text for none highlight in markdown

- sphinxcontrib/jupyter/writers/translate_all.py
this will assume the specified dependent file should be located where the notebook is saved and is agnostic towards nested directories in the called `_static` location.
> FIX: make more robust to varying directory structures for dependent files

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/writers/translate_all.py
- sphinxcontrib/jupyter/writers/translate_code.py
add ability to specify a urlprefix for references (between notebooks) that will send users to the web location (rather than locally). 
``jupyter_target_html_urlprefix = "prefix path"``
> FEAT: add jupyter_target_html_urlprefix option

- sphinxcontrib/jupyter/writers/translate_code.py
This PR adds metadata to each code-block to set visibility of the `output` block. 
It can be used to hide output using ``:class: hide-output``
> FEAT: add metadata for hide-output pass through to an nb_executor

- .travis.yml
- README.rst
- sphinxcontrib/jupyter/writers/translate_all.py
- sphinxcontrib/jupyter/writers/translate_code.py
This PR makes sphinx >= 1.8 supported.
The main issue was with math_block. Math nodes do not have a latex attribute anymore 
with sphinx >= 1.8. Math nodes are now treated as every other node, i.e. a flag is raised
when the mode is activated, then the text (content) is written, then the
flag is down.
Closing #124
> Support sphinx >= 1.8

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/writers/translate_all.py
Allow easier support for working with local images in notebooks when overriding a conf.py.
A local command can then be used in sphinx Makefile to override the exisiting `conf.py`:
```
local:
@$(SPHINXBUILD) -M jupyter "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O) -D jupyter_images_urlpath=0
```
> FEAT: easier support for compiling notebooks with local images

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/directive/exercise.py
- sphinxcontrib/jupyter/writers/translate_all.py
- sphinxcontrib/jupyter/writers/utils.py
- tests/exercises.rst
- tests/index.rst
- tests/ipynb/exercises.ipynb
- tests/ipynb/index.ipynb
Hey @mmcky here is my first pass at making an `.. exercise` directive.
It seems to work pretty well for me, but isn't a totally clean/optimal implementation.
One place where I really had to do something I'm not proud of is in `JupyterTranslator.depart_literal_block`
Let me explain what I wanted, then I'll try to defend myself...
I wanted the ability to do something like
```rst
.. exercise::
:class: cfu
This is a check for understanding exercise
This is a note that has some *italic* and **bold** embedded
- list
- in
- exercise
.. code-block:: python
def foobar(x, y, z):
print(x, y, z)
And text after the code block
```
and have the entire exercise block -- code section and everything -- in a single markdown cell inside a `<blockquote>` element (html name for `>`).
The issue is that the …
> ENH: added exercises directive

- sphinxcontrib/jupyter/writers/translate_all.py
- tests/ipynb/index.ipynb
- tests/ipynb/inline.ipynb
- tests/ipynb/math.ipynb
- tests/ipynb/simple_notebook.ipynb
- tests/simple_notebook.rst
This PR fixes an issue when using `$` sign in text. When multiple `$` chars are used in markdown they are interpreted as math. To fix this the extension escape `$` using `\$` when writing any `text` into markdown cells.
> BUG: fix issue when parsing $ sign as special markdown syntax

- sphinxcontrib/jupyter/__init__.py
This PR: 
- add ``noop`` to stop blocking latex writer on RST that uses jupyter directives.
**Note:** this passes a no operation function for now.
> FIX: enable latex writer to compile

- sphinxcontrib/jupyter/writers/translate_all.py
This fix adjust relative `uri` references that are using `../` to produce corrected paths when compiling notebooks.
> FIX: adjust relative uri references

- sphinxcontrib/jupyter/writers/translate_all.py
This PR is just preventing the escaping of $ when it is a code block. Solves the issue [#173](https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/173) . But have not tested the consequences it might have otherwise. I reckon we dont need escaping in any of the code blocks right? @arnavs @jlperla @mmcky 
fixes #173
> added a check for code blocks when escaping

- sphinxcontrib/jupyter/writers/make_site.py
This is a bug fix for copying static assets to the correct folder defined by JUPYTER_WEBSITE + "_static"
> FIX: path was incorrect for copying some static assets

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/writers/translate_all.py
- sphinxcontrib/jupyter/writers/translate_code.py
This PR enables the option `jupyter_images_markdown` = `True` for writing image inclusion in text blocks in markdown, or `False` for writing in `html`. 
If this option is enabled it will remove support for `scale` attributes so the default value for this option is `False`.
> FEAT: add option to write images as markdown rather than html

- docs/conf.py
- docs/config-extension-coverage.rst
- docs/config-extension-html.rst
- docs/config-extension.rst
- docs/config-project.rst
- docs/examples.rst
- docs/index.rst
- docs/usage.rst
This PR applies edits and update to the documentation and removes the ``usage.rst`` in favour of the RST Conversion Gallery.
> UPDATE: Documentation

- sphinxcontrib/jupyter/__init__.py
Dask was throwing `yaml` errors on load. This suppresses them for now as fixed in dask (https://github.com/dask/dask/issues/4597)
fixes https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/203
> BUG: suppress yaml warnings for now, remove once dask is > 0.45

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/builders/jupyter.py
- sphinxcontrib/jupyter/writers/execute_nb.py
- sphinxcontrib/jupyter/writers/utils.py
This PR adds the functionality to add dependencies of files and folders in the source directory in the following manner : 
```
jupyter_dependencies = {
<dir> : ['file1', 'file2'],
{<dir>}/<file.rst> : ['file1']
}
```
At present, the values are file names, which are assumed to be in the same directory as the source keys. 
fixes #228
> ENH: Added functionality to specify the dependencies in config

- sphinxcontrib/jupyter/writers/translate_all.py
This addresses #247
I believe we can always count on `uri` being a string and the `len` function being well defined for the type, but that is one vulnerability with this attempted fix.
> Fix julia build by checking lengh of `uri` string before accessing first element

- setup.cfg
This PR adjusts versions to follow the main version in `setup.py` and doesn't append `dev{date}` to the builds.
> Remove egg cfg to remove dev status on version releases

- tests/base/ipynb/literal_include.ipynb
- tests/base/literal_include.rst
This PR adds a test case to `base` set of notebook tests for class attributes on ``.. literalinclude::``
> TEST: add :class: attribute test for literalinclude

- docs/config-example.rst
- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/builders/jupyter.py
- sphinxcontrib/jupyter/writers/jupyter.py
- sphinxcontrib/jupyter/writers/translate_all.py
- sphinxcontrib/jupyter/writers/translate_code.py
- tests/website/conf.py
The url set in `jupyter_images_urlpath` will only be prepended to download notebooks as of now. 
fixes #251 
@mmcky I have not renamed the variable though. Let me know if you come up with a name
> ENH: Setting jupyter_images_urlpath only for downloads folder

- sphinxcontrib/jupyter/writers/translate_all.py
- tests/base/conf.py
- tests/base/ipynb/index.ipynb
- tests/base/ipynb/slides.ipynb
- tests/base/slides.rst
This PR fixes bug #226 
The following `RST`
```RST
Slide: Should have 2 code blocks as fragments (test)
++++++++++++++++++++++++++++++++++++++++++++++++++++
.. jupyter::
:slide-type: fragment
.. code:: ipython3
fibonacci_functional = (lambda n, first=1, second=1:
[] if n == 0 else
[first] + fibonacci_functional(n - 1, second, first + second))
.. jupyter::
:slide-type: fragment
.. code:: ipython3
for k in fibonacci_functional(10):print(k,end=' ')
```
is now rendered as
in `tests/base/slides.rst`
> Fix: slide fragment option not getting parsed correctly

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/builders/jupyter.py
- sphinxcontrib/jupyter/writers/execute_nb.py
- sphinxcontrib/jupyter/writers/make_site.py
This PR implements the feature to execute notebooks in `_downloads` folder.
To enable this feature, one has to set `jupyter_download_nb_execute` variable to `True` in config
> FEAT: Execute downloaded notebooks

- sphinxcontrib/jupyter/builders/jupyter.py
> FIX: fix bulk copy of static for all builder targets

- tests/base/ipynb/syntax.ipynb
- tests/base/syntax.rst
This tests `$` vs `\$` in the source RST
> TEST: add test cases for escape syntax

- sphinxcontrib/jupyter/__init__.py
Addressed #319 by working around potential YAML versions that don't support `warnings()` function call.
> Added protective code to support more versions of YAML package

- setup.py
- sphinxcontrib/jupyter/writers/execute_nb.py
Dask less then `2.10` uses a different data structure for `startstops` in `get_task_stream` then the newer version.
>  Fixing versions of dask to prevent code syntax issues

- sphinxcontrib/jupyter/builders/jupyter.py
- sphinxcontrib/jupyter/writers/execute_nb.py
Throws an exit code of 1 when there is a `fail` status for any lecture during the execution of its code cells.
> Throwing an exit code of 1 when there is an error in coverage

- sphinxcontrib/jupyter/writers/translate_all.py
checking the length of the bullets array before popping in enumerate list
> BUG: bullets array pop in enumerated list. 

- .travis.yml
- setup.py
This PR update version to 0.5.5 for new release, removes testing for `python=2.7`, and adds testing for `python=3.8`
> update version to 0.5.5

- .travis.yml
- setup.py
This PR removes the early version restrictions for `dask` in the `setup.py` due to https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/314/files
> Remove early version requirements for dask

- sphinxcontrib/jupyter/builders/jupyter.py
Implements #317 
This PR will add `next` and `previous` document metadata to the generated notebooks. 
Such as:
```json
"metadata": {
"date": 1591753649.837961,
"filename": "index.rst",
"kernelspec": {
"display_name": "Python",
"language": "python3",
"name": "python3"
},
"next_doc": {
"link": "index_toc",
"title": "Table of Contents"
},
"title": "Python Programming for Economics and Finance"
},
```
If metadata is valid:
1. `next` is referenced by `nb.metadata.next_doc`
2. `previous` is referenced by `nb.metadata.prev_doc`
> ENH: add next and prev document metadata to notebook meta

- sphinxcontrib/jupyter/__init__.py
- sphinxcontrib/jupyter/builders/jupyter.py
This PR adds support for next and prev metadata to exclude items, such as hidden TOC elements. 
You can add in `conf.py`
```rst
jupyter_nextprev_ignore = [<docname>, ...]
```
> ENH: Add support for exclusion of Next and Previous metadata in conf.py

- setup.py
- sphinxcontrib/jupyter/builders/jupyter.py
This PR fixes a bug where inline elements in a title can break the title name metadata stored in the notebook when the builder parses titles for `next` and `prev` metadata.
> FIX: fix bug with mixed titles having many children for next and prev metadata

- sphinxcontrib/jupyter/builders/jupyter.py
This PR simplifies the metadata added to notebooks by not including metadata if a relation is not found in the notebook
> FIX: Simply interface with template layer for next and prev metadata in notebooks
